import { describe, it, expect, beforeAll } from '@jest/globals';
import { handleRequest } from '../index';
import { CloudflareEnv } from '../types';

// Mock environment for testing
const mockEnv: CloudflareEnv = {
  DB: {
    prepare: jest.fn().mockReturnValue({
      bind: jest.fn().mockReturnValue({
        first: jest.fn(),
        all: jest.fn(),
        run: jest.fn()
      })
    }),
    exec: jest.fn()
  } as any,
  AVATARS: {} as any,
  JWT_SECRET: 'test-secret-key',
  BCRYPT_ROUNDS: '10',
  ENVIRONMENT: 'test'
};

// Mock JWT token for testing (this would normally be generated by Phase 2 auth)
const mockJWT = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJ1c2VybmFtZSI6ImFkbWluIiwiZW1haWwiOiJhZG1pbkBleGFtcGxlLmNvbSIsInJvbGUiOiJhZG1pbiIsInBlcm1pc3Npb25zIjpbInVzZXJzLnZpZXciLCJ1c2Vycy5jcmVhdGUiLCJ1c2Vycy5lZGl0IiwidXNlcnMuZGVsZXRlIiwiYWRtaW4udmlldyJdLCJpYXQiOjE2NDEwMjQwMDAsImV4cCI6OTk5OTk5OTk5OX0.test-signature';

describe('API Integration Tests', () => {
  describe('Health Check', () => {
    it('should return healthy status', async () => {
      const request = new Request('http://localhost/api/health', {
        method: 'GET'
      });

      const response = await handleRequest(request, mockEnv);
      const data = await response.json();

      expect(response.status).toBe(200);
      expect(data.success).toBe(true);
      expect(data.data.status).toBe('healthy');
      expect(data.data.environment).toBe('test');
    });
  });

  describe('CORS Handling', () => {
    it('should handle OPTIONS preflight request', async () => {
      const request = new Request('http://localhost/api/users', {
        method: 'OPTIONS',
        headers: {
          'Origin': 'https://panel.example.com'
        }
      });

      const response = await handleRequest(request, mockEnv);

      expect(response.status).toBe(200);
      expect(response.headers.get('Access-Control-Allow-Origin')).toBeTruthy();
      expect(response.headers.get('Access-Control-Allow-Methods')).toBeTruthy();
    });
  });

  describe('Authentication Required Routes', () => {
    it('should return 401 for requests without authorization', async () => {
      const request = new Request('http://localhost/api/users', {
        method: 'GET'
      });

      const response = await handleRequest(request, mockEnv);
      const data = await response.json();

      expect(response.status).toBe(401);
      expect(data.success).toBe(false);
      expect(data.error.message).toContain('Authorization token required');
    });

    it('should return 401 for requests with invalid token', async () => {
      const request = new Request('http://localhost/api/users', {
        method: 'GET',
        headers: {
          'Authorization': 'Bearer invalid-token'
        }
      });

      const response = await handleRequest(request, mockEnv);
      const data = await response.json();

      expect(response.status).toBe(401);
      expect(data.success).toBe(false);
      expect(data.error.message).toContain('Invalid or expired token');
    });
  });

  describe('Route Not Found', () => {
    it('should return 404 for unknown routes', async () => {
      const request = new Request('http://localhost/api/unknown', {
        method: 'GET'
      });

      const response = await handleRequest(request, mockEnv);
      const data = await response.json();

      expect(response.status).toBe(404);
      expect(data.success).toBe(false);
      expect(data.error.message).toBe('Route not found');
      expect(data.error.code).toBe('NOT_FOUND');
    });
  });

  describe('Method Not Allowed', () => {
    it('should return 405 for unsupported methods', async () => {
      const request = new Request('http://localhost/api/users', {
        method: 'PATCH' // Not supported on this route
      });

      const response = await handleRequest(request, mockEnv);
      const data = await response.json();

      expect(response.status).toBe(405);
      expect(data.success).toBe(false);
      expect(data.error.message).toBe('Method not allowed');
      expect(data.error.code).toBe('METHOD_NOT_ALLOWED');
    });
  });

  describe('API Route Validation', () => {
    const testRoutes = [
      { path: '/api/users', methods: ['GET', 'POST'] },
      { path: '/api/users/profile', methods: ['GET', 'PUT'] },
      { path: '/api/users/profile/password', methods: ['PUT'] },
      { path: '/api/users/profile/avatar', methods: ['POST'] },
      { path: '/api/users/profile/settings', methods: ['GET', 'PUT'] },
      { path: '/api/roles', methods: ['GET'] },
      { path: '/api/permissions', methods: ['GET'] },
      { path: '/api/permissions/check', methods: ['POST'] }
    ];

    testRoutes.forEach(({ path, methods }) => {
      it(`should recognize route ${path}`, async () => {
        for (const method of methods) {
          const request = new Request(`http://localhost${path}`, {
            method,
            headers: method !== 'GET' ? { 'Content-Type': 'application/json' } : undefined,
            body: method !== 'GET' ? JSON.stringify({}) : undefined
          });

          const response = await handleRequest(request, mockEnv);
          
          // Should not be 404 (route exists) or 405 (method allowed)
          expect(response.status).not.toBe(404);
          expect(response.status).not.toBe(405);
          
          // Should be 401 (auth required) which means route exists
          expect(response.status).toBe(401);
        }
      });
    });

    it('should recognize dynamic user routes', async () => {
      const dynamicRoutes = [
        '/api/users/123',
        '/api/users/456/roles',
        '/api/users/789/permissions',
        '/api/users/101/activity',
        '/api/users/102/suspend',
        '/api/users/103/activate'
      ];

      for (const path of dynamicRoutes) {
        const request = new Request(`http://localhost${path}`, {
          method: 'GET'
        });

        const response = await handleRequest(request, mockEnv);
        
        // Should not be 404 (route exists)
        expect(response.status).not.toBe(404);
        
        // Should be 401 (auth required) which means route exists
        expect(response.status).toBe(401);
      }
    });
  });

  describe('Input Validation', () => {
    it('should validate user ID parameters', async () => {
      const request = new Request('http://localhost/api/users/invalid-id', {
        method: 'GET',
        headers: {
          'Authorization': `Bearer ${mockJWT}`
        }
      });

      const response = await handleRequest(request, mockEnv);
      const data = await response.json();

      expect(response.status).toBe(400);
      expect(data.success).toBe(false);
      expect(data.error.message).toBe('Invalid user ID');
      expect(data.error.code).toBe('INVALID_ID');
    });
  });

  describe('Error Handling', () => {
    it('should handle internal server errors gracefully', async () => {
      // Mock an error in the database
      const failingEnv = {
        ...mockEnv,
        DB: {
          prepare: jest.fn().mockImplementation(() => {
            throw new Error('Database connection failed');
          })
        }
      };

      const request = new Request('http://localhost/api/health', {
        method: 'GET'
      });

      const response = await handleRequest(request, failingEnv);
      const data = await response.json();

      expect(response.status).toBe(500);
      expect(data.success).toBe(false);
      expect(data.error.message).toBe('Internal server error');
      expect(data.error.code).toBe('INTERNAL_ERROR');
    });
  });
});