# Environment configuration for ${environment}
# Generated by Terraform - DO NOT EDIT MANUALLY

# Application
APP_NAME=Pterodactyl
APP_ENV=${environment}
APP_DEBUG=false
APP_URL=https://${domain_name}
APP_KEY=${app_key}
APP_TIMEZONE=UTC

# Database (Cloudflare D1)
DB_CONNECTION=d1
D1_DATABASE_ID=${d1_database_id}
DB_ENCRYPTION_KEY=${db_encryption_key}

# File Storage (Cloudflare R2)
FILESYSTEM_DRIVER=r2
R2_FILES_BUCKET=${r2_files_bucket}
R2_BACKUPS_BUCKET=${r2_backups_bucket}

# Cache (Cloudflare KV)
CACHE_DRIVER=kv
CACHE_KV_NAMESPACE=${cache_namespace_id}

# Sessions (Cloudflare KV)
SESSION_DRIVER=kv
SESSION_KV_NAMESPACE=${sessions_namespace_id}

# Queue (Cloudflare Queues)
QUEUE_CONNECTION=cloudflare

# Mail Configuration
MAIL_DRIVER=smtp
MAIL_HOST=smtp.mailgun.org
MAIL_PORT=587
MAIL_USERNAME=
MAIL_PASSWORD=
MAIL_ENCRYPTION=tls
MAIL_FROM_ADDRESS=noreply@${domain_name}
MAIL_FROM_NAME="Pterodactyl Panel"

# Migration Configuration
MIGRATION_MODE=serverless
LEGACY_API_ENABLED=true

# Security
TRUSTED_PROXIES=
RECAPTCHA_ENABLED=false
RECAPTCHA_WEBSITE_KEY=
RECAPTCHA_SECRET_KEY=

# Analytics
ANALYTICS_ENABLED=true

# Monitoring
SENTRY_ENABLED=false
SENTRY_DSN=